import 'package:flutter/widgets.dart';

class S {
  S(this.locale);
  final Locale locale;
  bool get ar => locale.languageCode == 'ar';
  String t(String key) => (_values[key] ?? const ['', ''])[ar ? 1 : 0];
  static const _values = <String, List<String>>{
    'dashboard': ['Dashboard', 'لوحة التحكم'],
    'calendar': ['Calendar', 'التقويم'],
    'archive': ['Archive', 'الأرشيف'],
    'settings': ['Settings', 'الإعدادات'],
    'search': ['Search events', 'بحث في المناسبات'],
    'add': ['Add event', 'إضافة مناسبة'],
    'upcoming': ['Upcoming events', 'المناسبات القادمة'],
    'next': ['Next up', 'المناسبة التالية'],
    'empty': ['No events yet', 'لا توجد مناسبات بعد'],
    'title': ['Title', 'العنوان'],
    'description': ['Description', 'الوصف'],
    'date': ['Date', 'التاريخ'],
    'time': ['Time', 'الوقت'],
    'category': ['Category', 'التصنيف'],
    'save': ['Save', 'حفظ'],
    'cancel': ['Cancel', 'إلغاء'],
    'edit': ['Edit event', 'تعديل المناسبة'],
    'delete': ['Delete', 'حذف'],
    'restore': ['Restore', 'استعادة'],
    'details': ['Event details', 'تفاصيل المناسبة'],
    'appearance': ['Appearance', 'المظهر'],
    'language': ['Language', 'اللغة'],
    'light': ['Light', 'فاتح'],
    'dark': ['Dark', 'داكن'],
    'system': ['System', 'النظام'],
    'import': ['Import JSON', 'استيراد JSON'],
    'export': ['Export JSON', 'تصدير JSON'],
    'data': ['Data portability', 'نقل البيانات'],
    'sort': ['Sort', 'ترتيب'],
    'soonest': ['Soonest', 'الأقرب'],
    'latest': ['Latest', 'الأبعد'],
    'name': ['Name', 'الاسم'],
    'days': ['Days', 'أيام'],
    'hours': ['Hours', 'ساعات'],
    'minutes': ['Minutes', 'دقائق'],
    'seconds': ['Seconds', 'ثوانٍ'],
    'all': ['All', 'الكل'],
    'personal': ['Personal', 'شخصي'],
    'work': ['Work', 'عمل'],
    'travel': ['Travel', 'سفر'],
    'health': ['Health', 'صحة'],
    'other': ['Other', 'أخرى'],
    'preview': ['Import preview', 'معاينة الاستيراد'],
    'merge': ['Merge', 'دمج'],
    'replace': ['Replace all', 'استبدال الكل'],
    'invalid': [
      'The file is not a valid Movia export.',
      'الملف ليس تصديراً صالحاً من موفيا.',
    ],
    'imported': ['Import completed.', 'اكتمل الاستيراد.'],
    'exported': ['Export completed.', 'اكتمل التصدير.'],
    'archived': ['Archived', 'تمت الأرشفة'],
    'confirmDelete': [
      'Delete this event permanently?',
      'حذف هذه المناسبة نهائياً؟',
    ],
    'events': ['events', 'مناسبات'],
    'noArchived': ['No archived events', 'لا توجد مناسبات مؤرشفة'],
    'birthday': ['Birthday', 'عيد ميلاد'],
    'education': ['Education', 'تعليم'],
    'finance': ['Finance', 'مالية'],
    'created': ['Created', 'أُنشئت'],
    'updated': ['Last updated', 'آخر تحديث'],
    'today': ['Today', 'اليوم'],
    'tomorrow': ['Tomorrow', 'غداً'],
    'thisWeek': ['This Week', 'هذا الأسبوع'],
    'thisMonth': ['This Month', 'هذا الشهر'],
    'later': ['Later', 'لاحقاً'],
    'open': ['Open', 'فتح'],
    'duplicate': ['Duplicate', 'تكرار'],
    'actions': ['Actions', 'إجراءات'],
    'emptyMessage': [
      'Create an event to start your next countdown.',
      'أنشئ مناسبة لبدء العد التنازلي التالي.',
    ],
    'noMatches': ['No matching events', 'لا توجد مناسبات مطابقة'],
    'searchMessage': ['Try a different search term.', 'جرّب عبارة بحث مختلفة.'],
    'archiveMessage': [
      'Archived events will appear here.',
      'ستظهر المناسبات المؤرشفة هنا.',
    ],
    'calendarEmpty': ['No events this month', 'لا توجد مناسبات هذا الشهر'],
    'calendarMessage': [
      'Add an event to see it on the calendar.',
      'أضف مناسبة لعرضها في التقويم.',
    ],
    'openWidget': ['Open Desktop Widget', 'فتح أداة سطح المكتب'],
    'desktopWidget': ['Desktop Widget', 'أداة سطح المكتب'],
    'widgetStyle': ['Widget style', 'نمط الأداة'],
    'selectedEvent': ['Selected event', 'المناسبة المحددة'],
    'alwaysOnTop': ['Always on top', 'دائماً في المقدمة'],
    'lockPosition': ['Lock position', 'قفل الموضع'],
    'opacity': ['Background opacity', 'شفافية الخلفية'],
    'startWidget': ['Start widget with Movia', 'تشغيل الأداة مع موفيا'],
    'startWindows': ['Start with Windows', 'التشغيل مع ويندوز'],
    'compact': ['Compact', 'مدمج'],
    'countdown': ['Countdown', 'عد تنازلي'],
    'widgetNoEvent': ['No event selected', 'لم يتم تحديد مناسبة'],
    'selectEvent': ['Select event', 'تحديد مناسبة'],
    'close': ['Close', 'إغلاق'],
    'applicationUpdates': ['Application Updates', 'تحديثات التطبيق'],
    'currentVersion': ['Current version', 'الإصدار الحالي'],
    'lastChecked': ['Last checked', 'آخر فحص'],
    'neverChecked': ['Never checked', 'لم يتم الفحص'],
    'checkUpdates': ['Check for updates', 'التحقق من التحديثات'],
    'automaticUpdates': [
      'Automatically check for updates',
      'التحقق التلقائي من التحديثات',
    ],
    'downloadInstall': ['Download and install', 'تنزيل وتثبيت'],
    'viewRelease': ['View release on GitHub', 'عرض الإصدار على GitHub'],
    'installUpdate': ['Install update', 'تثبيت التحديث'],
    'installConfirm': [
      'Movia will close and the installer will upgrade this installation. Your data remains in AppData.',
      'سيُغلق موفيا وسيقوم المثبّت بترقية التثبيت. ستبقى بياناتك في AppData.',
    ],
    'install': ['Install', 'تثبيت'],
    'about': ['About', 'حول'],
    'discardTitle': ['Discard changes?', 'تجاهل التغييرات؟'],
    'discardMessage': [
      'Your unsaved changes will be lost.',
      'ستفقد تغييراتك غير المحفوظة.',
    ],
    'keepEditing': ['Keep editing', 'متابعة التعديل'],
    'discard': ['Discard', 'تجاهل'],
    'update_idle': ['Ready to check.', 'جاهز للتحقق.'],
    'update_checking': ['Checking for updates…', 'جارٍ التحقق من التحديثات…'],
    'update_upToDate': ['Movia is up to date.', 'موفيا محدّث.'],
    'update_available': ['A new version is available.', 'يتوفر إصدار جديد.'],
    'update_downloading': ['Downloading update…', 'جارٍ تنزيل التحديث…'],
    'update_downloaded': ['Download completed.', 'اكتمل التنزيل.'],
    'update_installing': ['Installing…', 'جارٍ التثبيت…'],
    'update_networkUnavailable': ['Network unavailable.', 'الشبكة غير متاحة.'],
    'update_apiUnavailable': [
      'GitHub Releases is unavailable.',
      'خدمة إصدارات GitHub غير متاحة.',
    ],
    'update_invalidRelease': [
      'Invalid release metadata.',
      'بيانات الإصدار غير صالحة.',
    ],
    'update_downloadFailed': ['Download failed.', 'فشل التنزيل.'],
    'update_checksumMismatch': [
      'Checksum mismatch. The installer was deleted.',
      'بصمة الملف غير متطابقة. تم حذف المثبّت.',
    ],
    'update_cancelled': ['Download cancelled.', 'تم إلغاء التنزيل.'],
    'update_installerLaunchFailed': [
      'Installer launch failed.',
      'فشل تشغيل المثبّت.',
    ],
  };
}

S s(BuildContext context) => S(Localizations.localeOf(context));
